# Generated by Django 5.0.14 on 2026-09-12 19:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Renseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_renseignement_bdp', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('technique', 'Technique'), ('normatif', 'Normatif')], max_length=16)),
                ('titre', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('source', models.CharField(help_text='ex: NVD, CERT-FR, ANSSI, ISO', max_length=200)),
                ('reference_externe', models.CharField(blank=True, help_text='ex: CVE-2026-41823', max_length=200)),
                ('criticite', models.CharField(blank=True, choices=[('critique', 'Critique'), ('elevee', 'Élevée'), ('moyenne', 'Moyenne'), ('faible', 'Faible')], max_length=16)),
                ('taxonomie_categorie', models.CharField(blank=True, max_length=200)),
                ('taxonomie_editeur', models.CharField(blank=True, max_length=200)),
                ('taxonomie_produit', models.CharField(blank=True, max_length=200)),
                ('taxonomie_version', models.CharField(blank=True, max_length=100)),
                ('taxonomie_referentiel', models.CharField(blank=True, max_length=200)),
                ('decouvert_le', models.DateTimeField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='bdp.renseignement')),
            ],
            options={
                'ordering': ['-decouvert_le'],
                'indexes': [models.Index(fields=['taxonomie_editeur', 'taxonomie_produit'], name='bdp_renseig_taxonom_520def_idx'), models.Index(fields=['taxonomie_referentiel'], name='bdp_renseig_taxonom_6325be_idx')],
            },
        ),
    ]
