# Generated by Django 5.0.14 on 2026-09-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renseignement',
            name='cvss_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renseignement',
            name='cvss_vector',
            field=models.CharField(blank=True, help_text='ex: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H', max_length=100),
        ),
    ]
