# Generated by Django 5.0.14 on 2026-09-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdp', '0002_renseignement_cvss_score_renseignement_cvss_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='renseignement',
            name='nature',
            field=models.CharField(blank=True, choices=[('vulnerabilite', 'Vulnérabilité'), ('correctif', 'Correctif'), ('reglementaire', 'Réglementaire'), ('information', 'Information')], max_length=16),
        ),
        migrations.AddField(
            model_name='renseignement',
            name='url_source',
            field=models.URLField(blank=True, help_text="Lien vers l'avis/l'article d'origine, pour verification", max_length=500),
        ),
    ]
