# Generated by Django 5.0.14 on 2026-09-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdp', '0003_renseignement_nature_renseignement_url_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='renseignement',
            name='auteur',
            field=models.CharField(blank=True, help_text='Analyste ou organisme auteur, si distinct de la source', max_length=200),
        ),
        migrations.AddField(
            model_name='renseignement',
            name='cve_associees',
            field=models.JSONField(blank=True, default=list, help_text='CVE additionnelles au-dela de reference_externe'),
        ),
        migrations.AddField(
            model_name='renseignement',
            name='ioc_associees',
            field=models.JSONField(blank=True, default=list, help_text='Indicateurs de compromission (hash, IP, domaine...)'),
        ),
        migrations.AddField(
            model_name='renseignement',
            name='niveau_confiance',
            field=models.CharField(blank=True, choices=[('faible', 'Faible'), ('moyen', 'Moyen'), ('eleve', 'Élevé')], max_length=16),
        ),
        migrations.AddField(
            model_name='renseignement',
            name='secteur_concerne',
            field=models.CharField(blank=True, help_text='Secteur vise, si la source le precise', max_length=200),
        ),
        migrations.AddField(
            model_name='renseignement',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Mots-cles libres, ex: ['ransomware', 'KEV']"),
        ),
        migrations.AddField(
            model_name='renseignement',
            name='tlp',
            field=models.CharField(blank=True, choices=[('clear', 'TLP:CLEAR'), ('green', 'TLP:GREEN'), ('amber', 'TLP:AMBER'), ('red', 'TLP:RED')], help_text='Traffic Light Protocol', max_length=8),
        ),
    ]
