# Generated by Django 5.0.14 on 2026-09-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdp', '0004_renseignement_auteur_renseignement_cve_associees_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='renseignement',
            constraint=models.UniqueConstraint(fields=('source', 'reference_externe', 'decouvert_le'), name='renseignement_source_ref_revision_unique'),
        ),
    ]
