# Generated by Django 5.0.14 on 2026-09-14 19:15

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdp', '0005_renseignement_renseignement_source_ref_revision_unique'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='renseignement',
            index=django.contrib.postgres.indexes.GinIndex(fields=['titre'], name='idx_rens_titre_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='renseignement',
            index=django.contrib.postgres.indexes.GinIndex(fields=['taxonomie_produit'], name='idx_rens_produit_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='renseignement',
            index=django.contrib.postgres.indexes.GinIndex(fields=['taxonomie_editeur'], name='idx_rens_editeur_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='renseignement',
            index=django.contrib.postgres.indexes.GinIndex(fields=['taxonomie_referentiel'], name='idx_rens_referentiel_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
