# Generated by Django 5.0.14 on 2026-09-13 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActifCatalogueVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('maintenue', models.BooleanField(default=True)),
                ('sortie_le', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-sortie_le', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ActifCatalogueProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=200)),
                ('editeur', models.CharField(max_length=200)),
                ('produit', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('endoflife', 'endoflife.date'), ('manuel', 'Ajout manuel')], default='manuel', max_length=20)),
                ('identifiant_source', models.CharField(blank=True, help_text="ex: slug endoflife.date ('debian', 'ubuntu')", max_length=200)),
                ('maj_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['categorie', 'editeur', 'produit'],
                'indexes': [models.Index(fields=['editeur', 'produit'], name='catalogue_a_editeur_8c44a8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='actifcatalogueproduit',
            constraint=models.UniqueConstraint(fields=('categorie', 'editeur', 'produit'), name='uniq_categorie_editeur_produit'),
        ),
        migrations.AddField(
            model_name='actifcatalogueversion',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalogue.actifcatalogueproduit'),
        ),
        migrations.AddConstraint(
            model_name='actifcatalogueversion',
            constraint=models.UniqueConstraint(fields=('produit', 'version'), name='uniq_produit_version'),
        ),
    ]
