# Generated by Django 5.0.14 on 2026-09-12 19:24

import apps.bdc.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActifClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('technique', 'Technique'), ('normatif', 'Normatif')], max_length=16)),
                ('categorie', models.CharField(blank=True, max_length=200)),
                ('editeur', models.CharField(blank=True, max_length=200)),
                ('produit', models.CharField(blank=True, max_length=200)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('referentiel', models.CharField(blank=True, max_length=200)),
                ('ajoute_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['editeur', 'produit'], name='bdc_actifcl_editeur_e0cf35_idx')],
            },
        ),
        migrations.CreateModel(
            name='PreferenceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seuil_criticite', models.CharField(choices=[('critique', 'Critique'), ('elevee', 'Élevée et plus'), ('moyenne', 'Moyenne et plus')], default='elevee', max_length=16)),
                ('frequence', models.CharField(choices=[('immediat', 'Immediat'), ('quotidien', 'Quotidien'), ('hebdo', 'Hebdomadaire')], default='quotidien', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_renseignement_bdp', models.UUIDField(db_index=True)),
                ('statut', models.CharField(choices=[('a_traiter', 'À traiter'), ('en_cours', 'En cours de traitement'), ('clos', 'Clos'), ('non_applicable', 'Non applicable')], default='a_traiter', max_length=20)),
                ('justificatif', apps.bdc.fields.EncryptedTextField(blank=True, default='')),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('actif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitements', to='bdc.actifclient')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueTraitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evenement', models.CharField(max_length=100)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('traitement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='bdc.traitement')),
            ],
            options={
                'ordering': ['horodatage'],
            },
        ),
        migrations.AddIndex(
            model_name='traitement',
            index=models.Index(fields=['id_renseignement_bdp'], name='bdc_traitem_id_rens_d3b326_idx'),
        ),
        migrations.AddIndex(
            model_name='traitement',
            index=models.Index(fields=['statut'], name='bdc_traitem_statut_e7ac3d_idx'),
        ),
    ]
