# Generated by Django 5.0.14 on 2026-09-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenseignementConsulte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_renseignement_bdp', models.UUIDField(unique=True)),
                ('consulte_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='traitement',
            name='echeance',
            field=models.DateField(blank=True, help_text='Delai de traitement previsionnel', null=True),
        ),
    ]
