# Generated by Django 5.0.14 on 2026-09-13 11:18

import apps.bdc.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdc', '0002_renseignementconsulte_traitement_echeance'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitement',
            name='passage_cab',
            field=models.BooleanField(blank=True, help_text='Oui/Non — non renseigne si null', null=True),
        ),
        migrations.AddField(
            model_name='traitement',
            name='plan_action',
            field=apps.bdc.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='traitement',
            name='preuve_fichier',
            field=models.FileField(blank=True, null=True, upload_to='preuves/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='traitement',
            name='echeance',
            field=models.DateField(blank=True, help_text='Date previsionnelle de traitement', null=True),
        ),
        migrations.AlterField(
            model_name='traitement',
            name='statut',
            field=models.CharField(choices=[('a_traiter', 'À traiter'), ('en_cours', 'Démarré'), ('clos', 'Clos'), ('non_applicable', 'Non applicable')], default='a_traiter', max_length=20),
        ),
    ]
