# Generated by Django 5.0.14 on 2026-09-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdc', '0003_traitement_passage_cab_traitement_plan_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueActif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif_repr', models.CharField(max_length=300)),
                ('evenement', models.CharField(choices=[('ajout', 'Ajouté'), ('version', 'Version modifiée'), ('suppression_conserve', 'Retiré (historique conservé)'), ('suppression_purge', 'Retiré (historique purgé)')], max_length=30)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-horodatage'],
            },
        ),
    ]
