# Generated by Django 5.0.14 on 2026-09-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdc', '0004_historiqueactif'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencenotification',
            name='afficher_compteurs_nav',
            field=models.BooleanField(default=True),
        ),
    ]
