# Generated by Django 5.0.14 on 2026-09-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdc', '0005_preferencenotification_afficher_compteurs_nav'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_objet', models.CharField(choices=[('actif', 'Actif'), ('traitement', 'Traitement')], max_length=20)),
                ('action', models.CharField(choices=[('ajout', 'Ajout'), ('modification', 'Modification'), ('suppression', 'Suppression')], max_length=20)),
                ('objet_repr', models.CharField(max_length=300)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('utilisateur', models.CharField(blank=True, max_length=150)),
                ('horodatage', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-horodatage'],
            },
        ),
    ]
